spring.application.name=school management

app.admin.username=admin
app.admin.password=admin123

app.jwt.secret=change-this-secret-to-at-least-32-characters-long-for-hs256
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
spring.datasource.url=jdbc:postgresql://localhost:5432/school_management
spring.datasource.username=root
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.show-sql=true


server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param